import { LanguageCode } from '../types';

export interface LanguageConfigItem {
  code: LanguageCode;
  name: string;
  nativeName: string;
  aiLanguage: string;
  speechLanguage: string;
  voiceAliases: string[];
  geminiVoice: string;
  isVoiceSupported: boolean;
  voiceStatusLabel: string;
  voiceProviderDescription: string;
  testSentence: string;
}

export const languageConfig: Record<LanguageCode, LanguageConfigItem> = {
  gu: {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    aiLanguage: 'Gujarati (ગુજરાતી)',
    speechLanguage: 'gu-IN',
    voiceAliases: ['gu', 'gujarati', 'gu-in', 'gu_in'],
    geminiVoice: 'Kore',
    isVoiceSupported: true,
    voiceStatusLabel: 'Fully Supported (Native Gujarati Voice)',
    voiceProviderDescription: 'Native Gujarati Voice Engine (gu-IN) • Authentic Gujarati Pronunciation',
    testSentence: 'નમસ્તે, હું ન્યાયસાથી છું. હું તમને તમારા સરકારી અને કાનૂની કામને સરળતાથી સમજવામાં મદદ કરીશ.',
  },
  hi: {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिंदी',
    aiLanguage: 'Hindi (हिंदी)',
    speechLanguage: 'hi-IN',
    voiceAliases: ['hi', 'hindi', 'hi-in', 'hi_in'],
    geminiVoice: 'Kore',
    isVoiceSupported: true,
    voiceStatusLabel: 'Fully Supported (Native Hindi Voice)',
    voiceProviderDescription: 'Native Hindi Voice Engine (hi-IN) • Authentic Hindi Pronunciation',
    testSentence: 'नमस्ते, मैं न्यायसाथी हूँ। मैं आपके सरकारी और कानूनी कार्यों को आसानी से समझने में आपकी सहायता करूँगा।',
  },
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    aiLanguage: 'English',
    speechLanguage: 'en-IN',
    voiceAliases: ['en', 'english', 'en-in', 'en_in', 'en-us', 'en-gb'],
    geminiVoice: 'Puck',
    isVoiceSupported: true,
    voiceStatusLabel: 'Fully Supported (Native English Voice)',
    voiceProviderDescription: 'Native English Voice Engine (en-IN) • Standard Indian English',
    testSentence: 'Hello, I am NyayaSaathi. I will help you understand your government notices and legal procedures simply.',
  },
  bn: {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    aiLanguage: 'Bengali (বাংলা)',
    speechLanguage: 'bn-IN',
    voiceAliases: ['bn', 'bengali', 'bangla', 'bn-in', 'bn_in', 'bn-bd'],
    geminiVoice: 'Kore',
    isVoiceSupported: true,
    voiceStatusLabel: 'Fully Supported (Native Bengali Voice)',
    voiceProviderDescription: 'Native Bengali Voice Engine (bn-IN) • Authentic Bengali Pronunciation',
    testSentence: 'নমস্কার, আমি ন্যায়সাথী। আমি আপনাকে আপনার সরকারি ও আইনি নথিপত্র সহজ বাংলায় বুঝতে সাহায্য করব।',
  },
  mr: {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    aiLanguage: 'Marathi (मराठी)',
    speechLanguage: 'mr-IN',
    voiceAliases: ['mr', 'marathi', 'mr-in', 'mr_in'],
    geminiVoice: 'Kore',
    isVoiceSupported: true,
    voiceStatusLabel: 'Fully Supported (Native Marathi Voice)',
    voiceProviderDescription: 'Native Marathi Voice Engine (mr-IN) • Authentic Marathi Pronunciation',
    testSentence: 'नमस्कार, मी न्यायसाथी आहे. मी आपल्या सरकारी आणि कायदेशीर कामांची माहिती सोप्या मराठीत समजावून सांगण्यास मदत करेन.',
  },
  ta: {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    aiLanguage: 'Tamil (தமிழ்)',
    speechLanguage: 'ta-IN',
    voiceAliases: ['ta', 'tamil', 'ta-in', 'ta_in', 'ta-lk', 'ta-sg'],
    geminiVoice: 'Kore',
    isVoiceSupported: true,
    voiceStatusLabel: 'Fully Supported (Native Tamil Voice)',
    voiceProviderDescription: 'Native Tamil Voice Engine (ta-IN) • Authentic Tamil Pronunciation',
    testSentence: 'வணக்கம், நான் நியாயசாதி. உங்கள் அரசு ஆவணங்கள் மற்றும் சட்ட நடைமுறைகளை எளிய தமிழில் புரிந்து கொள்ள நான் உதவுவேன்.',
  },
  te: {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    aiLanguage: 'Telugu (తెలుగు)',
    speechLanguage: 'te-IN',
    voiceAliases: ['te', 'telugu', 'te-in', 'te_in'],
    geminiVoice: 'Kore',
    isVoiceSupported: true,
    voiceStatusLabel: 'Fully Supported (Native Telugu Voice)',
    voiceProviderDescription: 'Native Telugu Voice Engine (te-IN) • Authentic Telugu Pronunciation',
    testSentence: 'నమస్కారం, నేను న్యాయసాథిని. మీ ప్రభుత్వ పత్రాలు మరియు చట్టపరమైన పనులను సులభంగా అర్థం చేసుకోవడంలో నేను మీకు సహాయం చేస్తాను.',
  },
  kn: {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    aiLanguage: 'Kannada (ಕನ್ನಡ)',
    speechLanguage: 'kn-IN',
    voiceAliases: ['kn', 'kannada', 'kn-in', 'kn_in'],
    geminiVoice: 'Kore',
    isVoiceSupported: true,
    voiceStatusLabel: 'Fully Supported (Native Kannada Voice)',
    voiceProviderDescription: 'Native Kannada Voice Engine (kn-IN) • Authentic Kannada Pronunciation',
    testSentence: 'ನಮಸ್ಕಾರ, ನಾನು ನ್ಯಾಯಸಾಥಿ. ನಿಮ್ಮ ಸರ್ಕಾರಿ ಮತ್ತು ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಸರಳ ಕನ್ನಡದಲ್ಲಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ.',
  },
  ml: {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    aiLanguage: 'Malayalam (മലയാളം)',
    speechLanguage: 'ml-IN',
    voiceAliases: ['ml', 'malayalam', 'ml-in', 'ml_in'],
    geminiVoice: 'Kore',
    isVoiceSupported: true,
    voiceStatusLabel: 'Fully Supported (Native Malayalam Voice)',
    voiceProviderDescription: 'Native Malayalam Voice Engine (ml-IN) • Authentic Malayalam Pronunciation',
    testSentence: 'നമസ്കാരം, ഞാൻ ന്യായസാഥിയാണ്. നിങ്ങളുടെ സർക്കാർ രേഖകളും നിയമപരമായ കാര്യങ്ങളും ലളിതമായ മലയാളത്തിൽ മനസ്സിലാക്കാൻ ഞാൻ സഹായിക്കും.',
  },
  pa: {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    aiLanguage: 'Punjabi (ਪੰਜਾਬੀ)',
    speechLanguage: 'pa-IN',
    voiceAliases: ['pa', 'punjabi', 'pa-in', 'pa_in', 'panjabi'],
    geminiVoice: 'Kore',
    isVoiceSupported: true,
    voiceStatusLabel: 'Fully Supported (Native Punjabi Voice)',
    voiceProviderDescription: 'Native Punjabi Voice Engine (pa-IN) • Authentic Punjabi Pronunciation',
    testSentence: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, ਮੈਂ ਨਿਆਇਸਾਥੀ ਹਾਂ। ਮੈਂ ਤੁਹਾਡੇ ਸਰਕਾਰੀ ਅਤੇ ਕਾਨੂੰਨੀ ਕੰਮਾਂ ਨੂੰ ਸਰਲ ਪੰਜਾਬੀ ਵਿੱਚ ਸਮਝਣ ਵਿੱਚ ਤੁਹਾਡੀ ਮਦਦ ਕਰਾਂਗਾ।',
  },
  or: {
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    aiLanguage: 'Odia (ଓଡ଼ିଆ)',
    speechLanguage: 'or-IN',
    voiceAliases: ['or', 'odia', 'oriya', 'or-in', 'or_in', 'od-in'],
    geminiVoice: 'Kore',
    isVoiceSupported: false,
    voiceStatusLabel: 'Partially Supported (Text Explanation Complete • Native Voice In Development)',
    voiceProviderDescription: 'Odia Text Fully Supported • Native-Speaker Voice Model in Active Development',
    testSentence: 'ନମସ୍କାର, ମୁଁ ନ୍ୟାୟସାଥୀ। ଆପଣଙ୍କ ସରକାରୀ ଏବଂ ଆଇନଗତ କାର୍ଯ୍ୟକୁ ସରଳ ଭାଷାରେ ବୁଝିବାରେ ମୁଁ ସାହାଯ୍ୟ କରିବି।',
  },
};

export const SUPPORTED_LANGUAGE_CODES: LanguageCode[] = [
  'gu',
  'hi',
  'en',
  'bn',
  'mr',
  'ta',
  'te',
  'kn',
  'ml',
  'pa',
  'or',
];
